### ISSUE TITLE
htmx-2 regression: WebSocket extension no longer sends hx-vals along with calls

### ISSUE THREAD

**Issue by aral** [bigskysoftware/htmx-extensions#10]
In htmx-1, WebSocket calls sent the data in `hx-vals` attributes on elements that had `ws-send` defined on them (see passing test: https://github.com/bigskysoftware/htmx/pull/2416)

In htmx-2, WebSocket calls do not send `hx-vals` (see failing test: https://github.com/bigskysoftware/htmx-extensions/compare/main...aral:htmx-extensions:ws-hx-vals-test).

**Comment by aral** [comment]
Can we close this issue now that this has been implement in https://github.com/bigskysoftware/htmx/pull/2418?

**Comment by 1cg** [comment]
thank you!
