### ISSUE TITLE
Preload HTML forms

### ISSUE THREAD

**Issue by marisst** [bigskysoftware/htmx-extensions#105]
A nice enhancement of the [Preload extension](https://github.com/bigskysoftware/htmx-extensions/blob/main/src/preload/preload.js) would be to make it work on `<form hx-get preload>` elements.
- For `checkbox` and `radio` inputs, the `hx-get` should be preloaded on `mousedown` and `mouseover` events on `<label>` and `<input>` elements. Preload should be done alternating form data as if the input, which user interacted with, was selected.
- For `select` elements the `hx-get` should be preloaded on `focus` event. Preload should be done for all unselected options, alternating form data as if they were selected.

**Comment by Telroshan** [comment]
Implemented in #106
