### ISSUE TITLE
Preload extension preloads URLs but navigating there loads the data again

### ISSUE THREAD

**Issue by hirasso** [bigskysoftware/htmx-extensions#108]
Hi there! I might be confused on how the [preload extension](https://htmx.org/extensions/preload/) is supposed to work. See this screenshot of the chrome dev tools inspecting the network activity when navigating [htmx.org](https://htmx.org):

![Screen Shot 2021-11-26 at 13 14 48](https://user-images.githubusercontent.com/869813/143579845-2b171054-3024-4d43-85c7-9c052c1b1a1c.jpg)

Starting from the front page I hovered over the `docs` link in the main navigation. `preload.js` loaded the URL, as expected. Then I clicked on `docs` and now `htmx.js` loaded the URL again from the server, seemingly without using the preloaded data. As soon as the `docs` page had been rendered, moving the cursor just a little bit (it was still resting on the `docs` link), triggered `preload.js` again, resulting in loading the URL _again_ from the server. Same scenario with the `reference` link. Three server requests instead of one for each link with `preload`.

Am I missing something here? I would have expected that after preloading a URL, navigating towards it would not need another server request.

P.s.: I don't think the error in the console is related, it just points out a `404` for `https://unpkg.com/prismjs@1.20.0/components/prism-ecmascript.min.js`:

![Screen Shot 2021-11-26 at 13 24 32](https://user-images.githubusercontent.com/869813/143580648-2f45563f-49bd-43f8-86bd-93ac550ce81d.jpg)

**Comment by Telroshan** [comment]
Fixed in #106
