### ISSUE TITLE
Preload Ext adds loading styles to loaded elements

### ISSUE THREAD

**Issue by infuzu-yidisprei** [bigskysoftware/htmx-extensions#110]
If you use the htmx indicator attribute where basically it puts a special class on something and this is very useful to indicate a spinner/throbber for a loading state when a request is in progress. 

The issue is that the preload extension puts those styles on the appropriate indicator too early. My specific use case is that I put preload="mouseover" on some get elements. Normally, i use the hx-indicator to put a spinning icon on the element that will be changed to indicate that element will be changed. With preload, it puts that indicator on after I hover over it, even if I don't end up clicking.

**Comment by marisst** [comment]
Hello @infuzu-yidisprei,
This issue has been fixed in #106, but is waiting for approval to be merged. For now, you can use the updated version of the plugin with the fix from my fork: [preload.js](https://github.com/marisst/htmx-extensions/blob/main/src/preload/preload.js).

**Comment by Telroshan** [comment]
Fixed in #106
