### ISSUE TITLE
Preload extension results in duplicate network fetches

### ISSUE THREAD

**Issue by wingedpig** [bigskysoftware/htmx-extensions#118]
Using the preload extension, for hx-get I'm seeing a network fetch on mouse down, and then a duplicate network fetch on mouse up. Is this expected? Here is a sample page where you can see the behavior. Save it as a file, open it up and then open Developer tools to monitor network calls. It calls example.com, which fails with CORS errors, but in testing with a real site, I get the same duplicate network calls even when the calls succeed.

```
<html>
    <head>
        <script src="https://unpkg.com/htmx.org@1.9.5" integrity="sha384-xcuj3WpfgjlKF+FXhSQFQ0ZNr39ln+hwjN3npfM9VBnUskLolQAcN80McRIVOPuO" crossorigin="anonymous"></script>
        <script src="https://unpkg.com/htmx.org@1.9.5/dist/ext/preload.js"></script>
    </head>
    <body hx-ext="preload">
        <!-- post to /foo -->
        <a id="counter" href="#" hx-get="https://example.com" hx-target="#result" preload>
            Count Up
        </a>
        <output id="result"></output>
    </body>
</html>
```

**Comment by Telroshan** [comment]
Closing this as it's the usual Cache-Control issue. This issue is over 1 year old, and I _seem_ to remember the documentation was improved since then to emphasize on this important point

**Comment by zachsents** [comment]
This is still an issue, even with proper cache control headers. If the preload request doesn't finish before the click finishes, a second request is sent.

Only way it works is if the preload request completely finishes before clicking (like if preload="mouseover" and you wait a second before clicking). This isn't really how interactions happen in practice, though. Am I doing something wrong?

**Comment by Telroshan** [comment]
@zachsents yeah the preload extension is relatively basic and heavily relies on the browser to handle caching for us.
If the preload request isn't finished yet, then the browser didn't cache it yet and will fire a new request as it of course can't reuse the result of a still-pending request.

You likely want to work on the delay it takes the server to respond here though, one second sounds like a lot

If you need more time than say ~50-100 ms, you may want to trigger the preload on hover instead of the default mousedown, which would give you a higher time budget of say ~300-500 ms instead (or way more for slower users)
To check average interaction latency, you can try the [instanclick.io's click test](http://instantclick.io/click-test)

Hope this helps!

**Comment by zachsents** [comment]
@Telroshan for sure. Any plans to have the preload ext initialize the request and have a click wait for that same request, then swap in like a boost? If not, I'll write an extension at some point and report back.

What I've done for now, which is a nice speed increase is this:
```html
<a
  href="/path"
  hx-boost="true"
  hx-trigger="pointerdown[!ctrlKey]"
  onclick="if(!event.ctrlKey) event.preventDefault()"
>Click me</a>
```
Still get the head start from pointerdown, but maintains ctrl+click behavior. Of course, doesn't work for aggressive preloading using mouseover instead.

**Comment by Telroshan** [comment]
I'm not opposed to the idea, I can't think of a functional reason why this would be undesirable from the top of my head. Preloading is supposed to make htmx swap the preloaded response anyway, so cancelling the request and catching the still-in-flight preload instead would just make things faster as you said, can't think of a situation where it'd be an issue.
In terms of implementation though, I'd be curious to see how many code changes this requires to the extension, as well as how much complexity it adds. Depending on that, it might be relevant as a separate extension, or it might just make sense as an improvement of `preload` right away.
Anyway, in the worst case scenario (i.e. we don't accept this change into `preload` itself), this could still be a community extension instead, so if you're interested in implementing this, please feel free to do so!
