### ISSUE TITLE
SSE extension should dispatch close event

### ISSUE THREAD

**Issue by christophenne** [bigskysoftware/htmx-extensions#43]
Hi,

I am currently missing a way to listen for SSE close events. I think it would be fair to allow for listing to such events, in order to show some information to the user, for example. 

I could imagine the two following ways:
* dispatch an `htmx:sseClose` event
* dispatch the `htmx:sseBeforeMessage` and/or `htmx:sseMessage` event(s), even when the message type equals the `sse-close` message type.

Please let me know what you prefer or how I could do it instead, thanks!

**Comment by Telroshan** [comment]
(Cf the PR in progress about that matter #31)

**Comment by Telroshan** [comment]
Fixed in #31
