### ISSUE TITLE
hx-trigger sse:<event> doesn't work with multiple triggers

### ISSUE THREAD

**Issue by ghgsrt** [bigskysoftware/htmx-extensions#55]
I'm new to HTMX so perhaps this is an error of ignorance, but it seems when I try to use other triggers along side the sse trigger, the sse trigger ceases to function.

I'm trying to set it such that the server can ping the client when it needs to update, and obviously I'd like for it to fetch what it needs onload.

`<section hx-get="/room/$$rid/chat" hx-trigger="sse:updateChat, load"></section>`

Yet, with the above, when only `sse:updateChat` is listed it works flawlessly, but when load is also listed only the load will run while all sse's get ignored by this element.

**Comment by Telroshan** [comment]
Hey, SSE should support multiple triggers syntax since 85ac241
Are you using version `2.2.0` ? Earlier versions didn't support it indeed

**Comment by ghgsrt** [comment]
Yeah, I'm getting sse@2.2.0 via cdn. htmx@2.0.1 also cdn

**Comment by ghgsrt** [comment]
![image](https://github.com/user-attachments/assets/102434be-1f41-471b-9c69-4a6789101601)
Seems the file supplied through the cdn is missing the loop added in that commit.

**Comment by Telroshan** [comment]
@ghgsrt Seems there is an issue with this release indeed, that's weird

Noticed we're actually even at 2.2.1 now, and https://unpkg.com/htmx-ext-sse@2.2.1/sse.js seems to correctly have all of the latest changes, could you confirm?
I'll update the README to use latest version

**Comment by ghgsrt** [comment]
@Telroshan 2.2.1 works! Thanks
