### ISSUE TITLE
CDN reference not updated for json-enc extension?

### ISSUE THREAD

**Issue by rsansores** [bigskysoftware/htmx-extensions#77]
It looks like this url:

https://unpkg.com/htmx-ext-json-enc@2.0.0/json-enc.js

Is still pointing to code in v1.x?

**Comment by Telroshan** [comment]
Hey @rsansores , no it's indeed the v2, just not the latest! (See 594a21a and c86568a that aren't published yet)
We still have to publish the latest changes to the extensions packages

**Comment by Telroshan** [comment]
Version 2.0.1 has been published btw (see https://unpkg.com/htmx-ext-json-enc@latest), closing this
