### ISSUE TITLE
multi-swap default swapStyle

### ISSUE THREAD

**Issue by goamaral** [bigskysoftware/htmx-extensions#80]
I have set htmx.config.defaultSwapStyle = "outerHTML".
I expected multi-swap to use this as well but it defaults to "innerHTML".
`var elementSwapStyle = typeof (split[1]) !== 'undefined' ? split[1] : 'innerHTML'`
Any reason for this behaviour?

Also, any reason the hx-swap is not sent as a header?

Thank you for taking the time

**Comment by Telroshan** [comment]
Hey, as stated in the [multi-swap doc](https://github.com/bigskysoftware/htmx-extensions/blob/main/src/multi-swap/README.md#usage)
> Default swap method is innerHTML.

As for,
> Any reason for this behaviour?

Can't really tell as I wasn't there when it was written, one thing I can say is that if we were to change that default, it would be a breaking change, so for backwards compatibility concerns, we can't change it.
Though, note you could totally copy the extension locally and change the [default value](https://github.com/bigskysoftware/htmx-extensions/blob/main/src/multi-swap/multi-swap.js#L20) if you need it:
https://github.com/bigskysoftware/htmx-extensions/blob/d3333ee8dbdd4e44ee5482d4721cbe78e6f5eecb/src/multi-swap/multi-swap.js#L20

On another note, I personnally wouldn't recommend using this extension at all, as its premise is simply untrue:
> OOB requires HTML tags marked with hx-swap-oob attributes to be at the TOP level of HTML, which significantly limited its use. With OOB, it's impossible to swap multiple elements arbitrarily placed and nested in the DOM tree.

That is actually false, and has been for [3 years](https://github.com/bigskysoftware/htmx/pull/2119).
I had removed that mention in the lib's doc [last year](https://github.com/bigskysoftware/htmx/pull/2119) but I totally forgot it was also mentioned here.

So for a very personal opinion, I'd suggest simply using oob swap instead and no extension at all for this matter.

> Also, any reason the hx-swap is not sent as a header?

What would be the use of such header? Note that we don't send everything as headers, and new headers have been implemented over time as the community needed it, or suggested a usecase that felt relevant to us. So feel free to defend your opinion here, we can always be convinced. But we'll need more information about its usage!

**Comment by goamaral** [comment]
Hey, everything you stated sounds reasonable.
Thanks for taking the time.
